version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.4.9
    container_name: etcd
    networks:
      - postgres-cluster
    ports:
      - "2379:2379"
      - "2380:2380"
    command: >
      /usr/local/bin/etcd
      --name etcd0
      --data-dir /etcd-data
      --initial-advertise-peer-urls http://0.0.0.0:2380
      --listen-peer-urls http://0.0.0.0:2380
      --advertise-client-urls http://0.0.0.0:2379
      --listen-client-urls http://0.0.0.0:2379
      --initial-cluster etcd0=http://0.0.0.0:2380
      --initial-cluster-state new

  patroni-node1:
    image: patroni
    container_name: patroni-node1
    networks:
      - postgres-cluster
    ports:
      - "5432:5432"
    environment:
      - PATRONI_NAME=pg-node1
      - PATRONI_SCOPE=postgres-cluster
      - PATRONI_RESTAPI_LISTEN=0.0.0.0:8008
      - PATRONI_RESTAPI_CONNECT_ADDRESS=patroni-node1:8008
      - PATRONI_ETCD_HOSTS=etcd:2379
      - PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=patroni-node1:5432
      - PATRONI_POSTGRESQL_DATA_DIR=/var/lib/postgresql/data
      - PATRONI_SUPERUSER_USERNAME=postgres
      - PATRONI_SUPERUSER_PASSWORD=your_postgres_password
      - PATRONI_REPLICATION_USERNAME=replicator
      - PATRONI_REPLICATION_PASSWORD=replicator_password
    volumes:
      - ./patroni/node1:/var/lib/postgresql/data

  patroni-node2:
    image: patroni
    container_name: patroni-node2
    networks:
      - postgres-cluster
    environment:
      - PATRONI_NAME=pg-node2
      - PATRONI_SCOPE=postgres-cluster
      - PATRONI_RESTAPI_LISTEN=0.0.0.0:8008
      - PATRONI_RESTAPI_CONNECT_ADDRESS=patroni-node2:8008
      - PATRONI_ETCD_HOSTS=etcd:2379
      - PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=patroni-node2:5432
      - PATRONI_POSTGRESQL_DATA_DIR=/var/lib/postgresql/data
      - PATRONI_SUPERUSER_USERNAME=postgres
      - PATRONI_SUPERUSER_PASSWORD=your_postgres_password
      - PATRONI_REPLICATION_USERNAME=replicator
      - PATRONI_REPLICATION_PASSWORD=replicator_password
    volumes:
      - ./patroni/node2:/var/lib/postgresql/data

  patroni-node3:
    image: patroni
    container_name: patroni-node3
    networks:
      - postgres-cluster
    environment:
      - PATRONI_NAME=pg-node3
      - PATRONI_SCOPE=postgres-cluster
      - PATRONI_RESTAPI_LISTEN=0.0.0.0:8008
      - PATRONI_RESTAPI_CONNECT_ADDRESS=patroni-node3:8008
      - PATRONI_ETCD_HOSTS=etcd:2379
      - PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=patroni-node3:5432
      - PATRONI_POSTGRESQL_DATA_DIR=/var/lib/postgresql/data
      - PATRONI_SUPERUSER_USERNAME=postgres
      - PATRONI_SUPERUSER_PASSWORD=your_postgres_password
      - PATRONI_REPLICATION_USERNAME=replicator
      - PATRONI_REPLICATION_PASSWORD=replicator_password
    volumes:
      - ./patroni/node3:/var/lib/postgresql/data

  haproxy:
    image: haproxy:2.4
    container_name: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "5000:5000"
    networks:
      - postgres-cluster

networks:
  postgres-cluster:
    driver: bridge
